server:
  domain: user
  version: 1.0
  jwtSecret: 38324
  grpcAddress: "127.0.0.1:10001"

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: grpc_todo_list
  username: root
  password: root
  charset: utf8mb4

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379
  password:

log:
  user:
    level: debug 
    logFile: false
    logFilePrefix: "log/"